<link rel="stylesheet" href="/Project/2_Enterprise/Design/Applications/Photo_Library/Main_App_Layout/css/photo_library.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/Project/2_Enterprise/Design/Plugins/lightbox/css/lightbox.css" type="text/css" media="screen" />
<link rel="stylesheet" href="/Project/2_Enterprise/Design/Plugins/dropzone/css/dropzone.css" media="screen" />

<script type="text/javascript" src="/Project/2_Enterprise/Design/Applications/Photo_Library/Main_App_Layout/templates/cropper.js"></script>

<script type="text/javascript" src="/Project/2_Enterprise/Design/Plugins/lightbox/js/lightbox.min.js"></script>

<script type="text/javascript" src="/Project/2_Enterprise/Design/Plugins/LazyLoad/js/lazyLoad.min.js"></script>
<script type="text/javascript" src="/Project/2_Enterprise/Design/Applications/Photo_Library/Main_App_Layout/templates/dropzone_config.js"></script>
