<div id="articleContainer" class="clearfix">
	<div class="clearfix row">
	<div id="photo_chooser"></div>
		<div id="leftColumn" class="col-xs-2"> 
			%%APPLICATION_LEFT_COLUMN%%
		</div> 
		<div id="contentColumn" class="col-xs-10">
			<div id="applicationContent" class="clearfix">
				%%APPLICATION_CONTENT%%
			</div>
		</div>
	</div>
	
	%%POPUP_DIALOGS%%
	<div class="transparent_background hide"></div>
</div>

