
<div id="footer">
	<div class="clearfix">
		<ul class="fleft">
			<li><a href="/">Home</a></li>
			<li><a href="/about-starfish-web-design-philippines">About Us</a></li>
			<li><a href="/products-and-services">Products and Services</a></li>
			<li><a href="/our-web-design-portfolio">Our Portfolio</a></li>
			<li><a href="/get-started">Get A Quote</a></li>
<!-- 		</ul> -->
<!-- 		<ul class="fleft"> -->
			<li><a href="/careers">Careers</a></li>
			<li class="last"><a href="/contact-us">Contact Us</a></li>
		</ul>
		<div id="socialMedia" class="fright">
			<div class="fright">
				<!-- Place this tag where you want the +1 button to render. -->
				<div class="g-plusone"></div>
				
				<!-- Place this tag after the last +1 button tag. -->
<!-- 				<script type="text/javascript"> 
				  (function() {
				    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				    po.src = 'https://apis.google.com/js/plusone.js';
				    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
				  })();
				</script>-->
			</div>
			<div class="fright">
				<a target="_blank" class="facebook" href="https://www.facebook.com/WebDesignPhilippinesStarfish">facebook</a>
				<a target="_blank" class="twitter" href="https://twitter.com/starf1shweb">twitter</a>
				<a target="_blank" class="tumblr" href="http://starfishwebdesign.tumblr.com/">tumblr</a>
				<a target="_blank" class="linkedin" href="http://ph.linkedin.com/pub/stafish-internet-solutions-inc/28/284/951">linkedin</a>
				<a target="_blank" class="instagram" href="http://instagram.com/starfishweb">instagram</a>
				<a target="_blank" class="pinterest" href="http://www.pinterest.com/starfishweb/boards/">pinterest</a>
			</div>
		</div>
	</div>
	<div id="copyright" class="clearfix">
		<p><a href="/">Web Design Philippines</a>. Starfish &copy; 2013. All Rights Reserved</p>
	</div>
</div>