<ul class="nav nav-tabs" role="tablist" id="side_nav_tab">
	<li class="active">
		<a href="#part1" role="tab" data-toggle="tab">Part 1. Main Applicant Information</a>
	</li>
	<li>
		<a href="#part2" role="tab" data-toggle="tab">Part 2. Co-Applicant Information and Background</a>
	</li>
	<li class="" style="width:100%">
		<a href="#part3" role="tab" data-toggle="tab">Part 3.</a>
	</li>
	<li>
		<a href="#part4" role="tab" data-toggle="tab">Part 4. Anti-Terrorism Certificate</a>
	</li>
	<li>
		<a href="#part5" role="tab" data-toggle="tab">Part 5. Management System Questionnaire</a>
	</li>
	<li>
		<a href="#part6" role="tab" data-toggle="tab">Part 6. Technical Proposal</a>
	</li>
	<li>
		<a href="#part7" role="tab" data-toggle="tab">Part 7. Budget Proposal</a>
	</li>
	<li>
		<a href="#part8" role="tab" data-toggle="tab">Part 8. Grant application cover letter</a>
	</li>
	<li>
		<a href="#part9" role="tab" data-toggle="tab">Part 9. Data Universal Number system (DUNS)</a>
	</li>
	<li>
		<a href="#part10" role="tab" data-toggle="tab">Part 10. Certification</a>
	</li>
</ul>